force-app/main/default/objects/Custom_Search_Field__mdt/Custom_Search_Field__mdt.object-meta.xml
<CustomObject>
    <description>Used to define fields to display / filter on custom search page</description>
    <label>Custom Search Field</label>
    <pluralLabel>Custom Search Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Display_Field__c.field-meta.xml
<CustomField>
    <fullName>Display_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the field is queried and displayed as a column</description>
    <inlineHelpText>If checked, the field is queried and displayed as a column</inlineHelpText>
    <label>Display Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <description>Determines the order of the column displayed, field with lowest order is placed on the left</description>
    <inlineHelpText>Determines the order of the column displayed, field with lowest order is placed on the left</inlineHelpText>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Editable__c.field-meta.xml
<CustomField>
    <fullName>Editable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the field is editable. Note the field must be displayed in order to be edited</description>
    <inlineHelpText>If checked, the field is editable. Note the field must be displayed in order to be edited</inlineHelpText>
    <label>Editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Editable_By__c.field-meta.xml
<CustomField>
    <fullName>Editable_By__c</fullName>
    <description>Profiles which can edit the field, separated by comma (,)</description>
    <inlineHelpText>Profiles which can edit the field, separated by comma (,)</inlineHelpText>
    <label>Editable By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>The field on the sobject</description>
    <inlineHelpText>The field on the sobject</inlineHelpText>
    <label>Field</label>
    <metadataRelationshipControllingField>Custom_Search_Field__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Custom_Search_Fields</relationshipLabel>
    <relationshipName>Custom_Search_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Filter_Field__c.field-meta.xml
<CustomField>
    <fullName>Filter_Field__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the field is a filterable. Note the field doesn&apos;t need to be displayed</description>
    <inlineHelpText>If checked, the field is a filterable. Note the field doesn&apos;t need to be displayed</inlineHelpText>
    <label>Filter Field</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The sobject</description>
    <inlineHelpText>The sobject</inlineHelpText>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Custom_Search_Fields</relationshipLabel>
    <relationshipName>Custom_Search_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Custom_Search_Field__mdt/fields/Operators__c.field-meta.xml
<CustomField>
    <fullName>Operators__c</fullName>
    <description>The operators available for the filter field. Separate with semicolon (;). Available operators are: equals, greater than, less than, equal to blank, not equal to blank, contains</description>
    <inlineHelpText>The operators available for the filter field. Separate with comma (;). Available operators are: equals, greater than, less than, equal to blank, not equal to blank, contains</inlineHelpText>
    <label>Operators</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DM_CustomSearchField.cls
/*******************************************************************************************************
* Class Name      	: DM_CustomSearchField
* Description		: Data Layer - Selector for CMT Custom_Search_Field__mdt
* Author          	: Simplus - Yi Zhang
* Created On      	: 31/07/2020
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer				Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* Yi Zhang              31/07/2020		1000				Initial version
******************************************************************************************************/
public class DM_CustomSearchField {

    /**
    * @description 
    * @author Yi Zhang | 31/07/2020 
    * @param objectApiName 
    * @return List<Custom_Search_Field__mdt> 
    **/
    public static List<Custom_Search_Field__mdt> customSearchFieldDataByObject(String objectApiName) {
        return new List<Custom_Search_Field__mdt>([
            SELECT Id,
            Object__r.QualifiedApiName, 
            Field__r.QualifiedApiName, 
            Field__r.Label, 
            Display_Field__c, Filter_Field__c, Editable__c, Editable_By__c, Display_Order__c, Operators__c
            FROM Custom_Search_Field__mdt
            WHERE Object__r.QualifiedApiName = :objectApiName
            ORDER BY Display_Order__c ASC
        ]);
    }
}